# Generated by Django 3.1 on 2020-08-25 22:35

from django.db import migrations, models
import mapper.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(auto_created=True, default=mapper.models.new_key, max_length=128, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=models.CharField(default=mapper.models.new_key, max_length=128, unique=True),
        ),
    ]
