# Generated by Django 2.2.15 on 2020-08-26 10:18

from django.db import migrations, models
import mapper.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20200825_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=models.CharField(auto_created=True, default=mapper.models.new_url, max_length=128, unique=True),
        ),
    ]
