# Generated by Django 2.2.15 on 2020-08-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_auto_20200826_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='names',
            field=models.TextField(blank=True),
        ),
    ]
